import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import Footer from "../components/Footer";

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Niku Singh",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${dmSans.variable} antialiased text-gray-500 dark:text-gray-400 transition-all duration-300`}>
        <div className="min-h-screen flex flex-col">
          <div className="flex-1 px-4">{children}</div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
